break_into_partial_movies: false
camera_qualities:
  default_quality: high
  high:
    frame_rate: 60
    resolution: 1920x1080
  low:
    frame_rate: 15
    resolution: 854x480
  medium:
    frame_rate: 30
    resolution: 1280x720
  ultra_high:
    frame_rate: 60
    resolution: 3840x2160
directories:
  mirror_module_path: false
  output: /Users/lin/code/python/manim/Vid
  raster_images: /Users/lin/code/python/manim/Img/rImg
  sounds: /Users/lin/code/python/manim/Aud
  temporary_storage: /Users/lin/code/python/manim/tmp
  vector_images: /Users/lin/code/python/manim/Img/vImg
full_screen: false
style:
  background_color: '#333333'
  font: Consolas
tex:
  executable: latex
  intermediate_filetype: dvi
  template_file: tex_template.tex
  text_to_replace: '[tex_expression]'
universal_import_line: from manimlib import *
window_monitor: 0
window_position: UR
